#!/bin/zsh
export PDK=sky130A
#export PDK_ROOT=/usr/local/share/pdk/
#export PDK_ROOT=/home/rpgraca/eda_tools/share/pdk/
export PDK_ROOT=/home/rpgraca/.ciel/
export LD_LIBRARY_PATH=/home/rpgraca/git/klayout/bin-release:$LD_LIBRARY_PATH
export PATH=/home/rpgraca/git/klayout/bin-release:$PATH
export KLAYOUT_PATH=$PDK_ROOT/$PDK/libs.tech/klayout
# KLayout is linked against libpython3.12; the old `klayout` conda env was
# deleted, so use anaconda base (also py3.12) for the shared lib.
# LD_LIBRARY_PATH=$HOME/git/klayout/build-release:$HOME/anaconda3/lib/ ~/git/klayout/build-release/klayout
export LD_LIBRARY_PATH=$HOME/git/klayout/build-release:$HOME/anaconda3/lib/:$LD_LIBRARY_PATH
export PATH=$HOME/git/klayout/build-release:$PATH
export KLAYOUT_PYTHONPATH=$HOME/anaconda3/lib/python3.12/site-packages/

