/* Generated by Yosys 0.63+89 (git sha1 de99d67bb, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

module \$extern:simplemap:$adff:CLK_POLARITY=1'1:ARST_VALUE=1'0:ARST_POLARITY=0:WIDTH=1 (CLK, ARST, Q, D);
  input CLK;
  wire CLK;
  input ARST;
  wire ARST;
  output Q;
  wire Q;
  input D;
  wire D;
  (* src = "../v_files/reg_pix_rst.v:24.1-36.4" *)
  sky130_fd_sc_hd__dfrtp_1 _0_ (
    .CLK(CLK),
    .D(D),
    .Q(Q),
    .RESET_B(ARST)
  );
endmodule

module \$extern:simplemap:$and:Y_WIDTH=1:B_WIDTH=1:A_WIDTH=1:B_SIGNED=0:A_SIGNED=0 (Y, B, A);
  output Y;
  wire Y;
  input B;
  wire B;
  input A;
  wire A;
  sky130_fd_sc_hd__and2_0 _0_ (
    .A(A),
    .B(B),
    .X(Y)
  );
endmodule

module \$extern:simplemap:$mux:WIDTH=1 (Y, S, B, A);
  output Y;
  wire Y;
  input S;
  wire S;
  input B;
  wire B;
  input A;
  wire A;
  sky130_fd_sc_hd__mux2_1 _0_ (
    .A0(A),
    .A1(B),
    .S(S),
    .X(Y)
  );
endmodule

module \$extern:simplemap:$or:Y_WIDTH=1:B_WIDTH=1:A_WIDTH=1:B_SIGNED=0:A_SIGNED=0 (Y, B, A);
  output Y;
  wire Y;
  input B;
  wire B;
  input A;
  wire A;
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _0_ (
    .A(A),
    .SLEEP(B),
    .X(Y)
  );
endmodule

(* cells_not_processed =  1  *)
(* src = "../v_files/reg_pix_rst.v:1.1-44.10" *)
module reg_pix_rst(clk, rst, en_on, en_off, comp_out, ncomp_out, global_pix_rst, en_pix_rst, evt_on, evt_off, pix_rst);
  (* src = "../v_files/reg_pix_rst.v:2.11-2.14" *)
  input clk;
  wire clk;
  (* src = "../v_files/reg_pix_rst.v:2.16-2.19" *)
  input rst;
  wire rst;
  (* src = "../v_files/reg_pix_rst.v:2.21-2.26" *)
  input en_on;
  wire en_on;
  (* src = "../v_files/reg_pix_rst.v:2.28-2.34" *)
  input en_off;
  wire en_off;
  (* src = "../v_files/reg_pix_rst.v:2.36-2.44" *)
  input comp_out;
  wire comp_out;
  (* src = "../v_files/reg_pix_rst.v:2.46-2.55" *)
  input ncomp_out;
  wire ncomp_out;
  (* src = "../v_files/reg_pix_rst.v:2.57-2.71" *)
  input global_pix_rst;
  wire global_pix_rst;
  (* src = "../v_files/reg_pix_rst.v:2.73-2.83" *)
  input en_pix_rst;
  wire en_pix_rst;
  (* src = "../v_files/reg_pix_rst.v:3.12-3.18" *)
  output evt_on;
  wire evt_on;
  (* src = "../v_files/reg_pix_rst.v:3.20-3.27" *)
  output evt_off;
  wire evt_off;
  (* src = "../v_files/reg_pix_rst.v:4.12-4.19" *)
  output pix_rst;
  wire pix_rst;
  (* src = "../v_files/reg_pix_rst.v:24.1-36.4" *)
  wire _0_;
  (* src = "../v_files/reg_pix_rst.v:9.1-21.4" *)
  wire _1_;
  (* src = "../v_files/reg_pix_rst.v:42.19-42.35" *)
  wire _2_;
  (* src = "../v_files/reg_pix_rst.v:7.14-7.22" *)
  wire dout_off;
  (* src = "../v_files/reg_pix_rst.v:7.5-7.12" *)
  wire dout_on;
  (* src = "../v_files/reg_pix_rst.v:6.6-6.9" *)
  wire evt;
  (* src = "../v_files/reg_pix_rst.v:42.19-42.35" *)
  \$extern:simplemap:$and:Y_WIDTH=1:B_WIDTH=1:A_WIDTH=1:B_SIGNED=0:A_SIGNED=0  _3_ (
    .A(evt),
    .B(en_pix_rst),
    .Y(_2_)
  );
  (* src = "../v_files/reg_pix_rst.v:39.14-39.32" *)
  \$extern:simplemap:$or:Y_WIDTH=1:B_WIDTH=1:A_WIDTH=1:B_SIGNED=0:A_SIGNED=0  _4_ (
    .A(dout_on),
    .B(dout_off),
    .Y(evt)
  );
  (* src = "../v_files/reg_pix_rst.v:42.18-42.53" *)
  \$extern:simplemap:$or:Y_WIDTH=1:B_WIDTH=1:A_WIDTH=1:B_SIGNED=0:A_SIGNED=0  _5_ (
    .A(_2_),
    .B(global_pix_rst),
    .Y(pix_rst)
  );
  (* src = "../v_files/reg_pix_rst.v:24.1-36.4" *)
  \$extern:simplemap:$adff:CLK_POLARITY=1'1:ARST_VALUE=1'0:ARST_POLARITY=0:WIDTH=1  _6_ (
    .ARST(rst),
    .CLK(clk),
    .D(_0_),
    .Q(dout_off)
  );
  (* src = "../v_files/reg_pix_rst.v:9.1-21.4" *)
  \$extern:simplemap:$adff:CLK_POLARITY=1'1:ARST_VALUE=1'0:ARST_POLARITY=0:WIDTH=1  _7_ (
    .ARST(rst),
    .CLK(clk),
    .D(_1_),
    .Q(dout_on)
  );
  (* full_case = 32'd1 *)
  (* src = "../v_files/reg_pix_rst.v:14.12-14.17|../v_files/reg_pix_rst.v:14.9-19.12" *)
  \$extern:simplemap:$mux:WIDTH=1  _8_ (
    .A(dout_on),
    .B(comp_out),
    .S(en_on),
    .Y(_1_)
  );
  (* full_case = 32'd1 *)
  (* src = "../v_files/reg_pix_rst.v:29.12-29.18|../v_files/reg_pix_rst.v:29.9-34.12" *)
  \$extern:simplemap:$mux:WIDTH=1  _9_ (
    .A(dout_off),
    .B(ncomp_out),
    .S(en_off),
    .Y(_0_)
  );
  assign evt_off = dout_off;
  assign evt_on = dout_on;
endmodule
